export const GRADEBOOK_PERMISSIONS = [
  // Compatibility permissions for the deployed assessment ledger.
  "gradebook.view",
  "gradebook.setup.manage",
  "gradebook.assessment.manage",
  "gradebook.marks.enter",
  "gradebook.publish",
  "gradebook.report",

  // GradeBook dashboard and configuration.
  "gradebook.dashboard.view",
  "gradebook.scheme.view",
  "gradebook.scheme.manage",
  "gradebook.scheme.activate",
  "gradebook.term.view",
  "gradebook.term.manage",
  "gradebook.term.activate",
  "gradebook.term.close",
  "gradebook.term.archive",
  "gradebook.exam_type.view",
  "gradebook.exam_type.manage",
  "gradebook.exam_type.activate",
  "gradebook.exam_type.archive",
  "gradebook.grade_scale.view",
  "gradebook.grade_scale.manage",
  "gradebook.grade_scale.activate",
  "gradebook.grade_scale.archive",
  "gradebook.calculation_rules.view",
  "gradebook.calculation_rules.manage",
  "gradebook.calculation_rules.activate",
  "gradebook.component.view",
  "gradebook.component.manage",
  "gradebook.settings.manage",

  // Examinations, scheduling, and teacher assignments.
  "gradebook.exam.view",
  "gradebook.exam.create",
  "gradebook.exam.update",
  "gradebook.exam.activate",
  "gradebook.exam.cancel",
  "gradebook.exam.readiness.view",
  "gradebook.exam.schedule.view",
  "gradebook.exam.schedule.manage",
  "gradebook.exam.schedule.publish",
  "gradebook.exam.schedule.cancel",
  "gradebook.assignment.view",
  "gradebook.assignment.manage",
  "gradebook.assignment.override",

  // Marks workflow and imports.
  "gradebook.marks.view",
  "gradebook.marks.save_draft",
  "gradebook.marks.submit",
  "gradebook.marks.verify",
  "gradebook.marks.return",
  "gradebook.marks.approve",
  "gradebook.marks.lock",
  "gradebook.marks.progress.view",
  "gradebook.marks.view_progress",
  "gradebook.marks.special_status.enter",
  "gradebook.marks.special_status.verify",
  "gradebook.import.download_template",
  "gradebook.import.create",
  "gradebook.import.validate",
  "gradebook.import.apply",
  "gradebook.import.cancel",
  "gradebook.marks.export",

  // Results, adjustments, corrections, and publication.
  "gradebook.adjustment.request",
  "gradebook.adjustment.review",
  "gradebook.adjustment.approve",
  "gradebook.adjustment.reject",
  "gradebook.adjustment.apply",
  "gradebook.adjustment.view_audit",
  "gradebook.marks.reopen.request",
  "gradebook.marks.reopen.review",
  "gradebook.marks.reopen.approve",
  "gradebook.marks.reopen.execute",
  "gradebook.result.calculate",
  "gradebook.result.view",
  "gradebook.result.view_preview",
  "gradebook.result.approve",
  "gradebook.result.recalculate",
  "gradebook.result.publish",
  "gradebook.result.publication.prepare",
  "gradebook.result.revoke",
  "gradebook.result.withhold",
  "gradebook.result.release_withheld",
  "gradebook.result.view_published",
  "gradebook.result.view_own",
  "gradebook.result.view_linked_student",
  "gradebook.result.correction.request",
  "gradebook.result.correction.approve",
  "gradebook.result.republish",

  // Remarks, co-scholastic records, report cards, history, and analytics.
  "gradebook.remark.subject.enter",
  "gradebook.remark.enter_subject",
  "gradebook.remark.class_teacher.enter",
  "gradebook.remark.principal.enter",
  "gradebook.remark.template.manage",
  "gradebook.remark.verify",
  "gradebook.remark.approve",
  "gradebook.coscholastic.view",
  "gradebook.coscholastic.manage_areas",
  "gradebook.coscholastic.enter",
  "gradebook.coscholastic.submit",
  "gradebook.coscholastic.verify",
  "gradebook.coscholastic.approve",
  "gradebook.attendance_summary.view",
  "gradebook.attendance_summary.generate",
  "gradebook.attendance_summary.refresh",
  "gradebook.reportcard.template.view",
  "gradebook.reportcard.template.manage",
  "gradebook.reportcard.preview",
  "gradebook.reportcard.generate",
  "gradebook.reportcard.approve",
  "gradebook.reportcard.view",
  "gradebook.reportcard.reprint",
  "gradebook.history.view",
  "gradebook.history.view_student",
  "gradebook.history.view_versions",
  "gradebook.history.reprint",
  "gradebook.history.export_transcript",
  "gradebook.analytics.view_institution",
  "gradebook.analytics.view_branch",
  "gradebook.analytics.view_class_section",
  "gradebook.analytics.view_subject",
  "gradebook.analytics.view_student",
  "gradebook.analytics.view_own",
  "gradebook.analytics.export",
  "gradebook.audit.view"
] as const;

export type GradebookPermissionCode = (typeof GRADEBOOK_PERMISSIONS)[number];
