export const SCHOOLCAST_PERMISSIONS = [
  "schoolcast.dashboard.view",
  "schoolcast.communication.view",
  "schoolcast.communication.create",
  "schoolcast.communication.edit",
  "schoolcast.communication.submit",
  "schoolcast.communication.review",
  "schoolcast.communication.approve",
  "schoolcast.communication.reject",
  "schoolcast.communication.publish",
  "schoolcast.communication.schedule",
  "schoolcast.communication.cancel",
  "schoolcast.communication.archive",
  "schoolcast.communication.duplicate",
  "schoolcast.audience.create",
  "schoolcast.audience.preview",
  "schoolcast.audience.resolve",
  "schoolcast.audience.use_individual",
  "schoolcast.audience.use_custom_list",
  "schoolcast.recipient.view_masked_contact",
  "schoolcast.recipient.view_detail",
  "schoolcast.emergency.create",
  "schoolcast.emergency.preview",
  "schoolcast.emergency.publish",
  "schoolcast.emergency.cancel_pending",
  "schoolcast.emergency.delivery.view",
  "schoolcast.template.view",
  "schoolcast.template.create",
  "schoolcast.template.update",
  "schoolcast.template.activate",
  "schoolcast.template.deactivate",
  "schoolcast.template.provider_map",
  "schoolcast.channel.select",
  "schoolcast.channel.override_defaults",
  "schoolcast.provider.view",
  "schoolcast.provider.manage",
  "schoolcast.provider.test",
  "schoolcast.provider.enable_live",
  "schoolcast.provider.rotate_secret",
  "schoolcast.provider.suspend",
  "schoolcast.provider.health.view",
  "schoolcast.approval.view",
  "schoolcast.approval.action",
  "schoolcast.attachment.upload",
  "schoolcast.attachment.view",
  "schoolcast.attachment.delete",
  "schoolcast.preference.view_own",
  "schoolcast.preference.update_own",
  "schoolcast.preference.manage",
  "schoolcast.consent.view_own",
  "schoolcast.consent.manage_own",
  "schoolcast.consent.manage",
  "schoolcast.inbox.view",
  "schoolcast.inbox.read",
  "schoolcast.inbox.acknowledge",
  "schoolcast.homework.view",
  "schoolcast.homework.create",
  "schoolcast.homework.edit",
  "schoolcast.homework.submit",
  "schoolcast.homework.approve",
  "schoolcast.homework.publish",
  "schoolcast.homework.cancel",
  "schoolcast.homework.resend",
  "schoolcast.homework.delivery.view",
  "schoolcast.outbox.view",
  "schoolcast.outbox.view_payload_metadata",
  "schoolcast.outbox.cancel",
  "schoolcast.outbox.process_manual",
  "schoolcast.outbox.retry",
  "schoolcast.outbox.admin_reconcile",
  "schoolcast.delivery.view",
  "schoolcast.delivery.resend",
  "schoolcast.history.view",
  "schoolcast.history.export",
  "schoolcast.analytics.view",
  "schoolcast.analytics.export",
  "schoolcast.automation.view",
  "schoolcast.automation.manage",
  "schoolcast.settings.view",
  "schoolcast.settings.manage",
  "schoolcast.feature.manage",
  "schoolcast.test.run",
  "schoolcast.audit.view",
  "schoolcast.audit.export"
] as const;

export type SchoolCastPermissionCode = (typeof SCHOOLCAST_PERMISSIONS)[number];

const providerSecretPermissions = new Set<SchoolCastPermissionCode>([
  "schoolcast.provider.manage",
  "schoolcast.provider.enable_live",
  "schoolcast.provider.rotate_secret",
  "schoolcast.provider.suspend",
  "schoolcast.feature.manage"
]);

export const SCHOOLCAST_PRINCIPAL_PERMISSIONS = SCHOOLCAST_PERMISSIONS.filter(
  (permission) => !providerSecretPermissions.has(permission)
);

export const SCHOOLCAST_TEACHER_PERMISSIONS = [
  "schoolcast.dashboard.view",
  "schoolcast.communication.view",
  "schoolcast.inbox.view",
  "schoolcast.inbox.read",
  "schoolcast.inbox.acknowledge",
  "schoolcast.preference.view_own",
  "schoolcast.preference.update_own",
  "schoolcast.consent.view_own",
  "schoolcast.consent.manage_own",
  "schoolcast.homework.view",
  "schoolcast.homework.create",
  "schoolcast.homework.edit",
  "schoolcast.homework.submit",
  "schoolcast.homework.publish",
  "schoolcast.homework.cancel",
  "schoolcast.homework.resend",
  "schoolcast.homework.delivery.view",
  "schoolcast.attachment.upload",
  "schoolcast.attachment.view",
  "schoolcast.attachment.delete"
] as const satisfies readonly SchoolCastPermissionCode[];

export const SCHOOLCAST_STAFF_PERMISSIONS = [
  "schoolcast.inbox.view",
  "schoolcast.inbox.read",
  "schoolcast.inbox.acknowledge",
  "schoolcast.preference.view_own",
  "schoolcast.preference.update_own",
  "schoolcast.consent.view_own",
  "schoolcast.consent.manage_own"
] as const satisfies readonly SchoolCastPermissionCode[];

export const SCHOOLCAST_OFFICE_PERMISSIONS = SCHOOLCAST_STAFF_PERMISSIONS;